import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Keep from "~/components/Keep";
import Login from "~/components/Login";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Keep</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-zinc-800">
        {sessionData ? <Keep /> : <Login />}
      </main>
    </>
  );
};

export default Home;
