import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Keep from "~/components/Keep";
import Login from "~/components/Login";
import Spinner from "~/components/Spinner";

const Home: NextPage = () => {
  const { status } = useSession();
  return (
    <>
      <Head>
        <title>Keep</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/keep.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-zinc-800">
        {status === "loading" ? (
          <div className="flex min-h-screen items-center justify-center">
            <Spinner size={60} />
          </div>
        ) : status === "authenticated" ? (
          <Keep />
        ) : (
          <Login />
        )}
      </main>
    </>
  );
};

export default Home;
